/* eslint-disable @typescript-eslint/no-explicit-any */
import { db } from "@/lib/db";

// SOC 2 Trust Service Criteria — built-in control library
export const SOC2_CONTROLS = [
  {
    controlId:   "CC6.1",
    framework:   "SOC2" as const,
    category:    "Logical and Physical Access",
    title:       "Logical Access Security Measures",
    description: "The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security threats.",
    cweIds:      ["CWE-306","CWE-287","CWE-22","CWE-434"],
  },
  {
    controlId:   "CC6.2",
    framework:   "SOC2" as const,
    category:    "Logical and Physical Access",
    title:       "Access Provisioning and Removal",
    description: "Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users.",
    cweIds:      ["CWE-284","CWE-269","CWE-732"],
  },
  {
    controlId:   "CC6.3",
    framework:   "SOC2" as const,
    category:    "Logical and Physical Access",
    title:       "Credential Management",
    description: "The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets based on approved authorizations.",
    cweIds:      ["CWE-798","CWE-613","CWE-522","CWE-256"],
  },
  {
    controlId:   "CC6.6",
    framework:   "SOC2" as const,
    category:    "Logical and Physical Access",
    title:       "Security Threats from Outside",
    description: "The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.",
    cweIds:      ["CWE-89","CWE-79","CWE-78","CWE-918","CWE-943"],
  },
  {
    controlId:   "CC6.7",
    framework:   "SOC2" as const,
    category:    "Logical and Physical Access",
    title:       "Transmission of Data",
    description: "The entity restricts the transmission, movement, and removal of information to authorized internal and external users and processes.",
    cweIds:      ["CWE-319","CWE-311","CWE-942","CWE-614"],
  },
  {
    controlId:   "CC7.1",
    framework:   "SOC2" as const,
    category:    "System Operations",
    title:       "System Monitoring",
    description: "To meet its objectives, the entity uses detection and monitoring procedures to identify changes to configurations and new vulnerabilities.",
    cweIds:      ["CWE-770","CWE-400","CWE-209"],
  },
  {
    controlId:   "CC7.2",
    framework:   "SOC2" as const,
    category:    "System Operations",
    title:       "Anomaly Identification",
    description: "The entity monitors system components and the operation of controls to detect anomalies that indicate malicious acts, natural disasters, or errors.",
    cweIds:      ["CWE-20","CWE-601","CWE-116"],
  },
  {
    controlId:   "CC8.1",
    framework:   "SOC2" as const,
    category:    "Change Management",
    title:       "Change Management Process",
    description: "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures.",
    cweIds:      ["CWE-502","CWE-611","CWE-494"],
  },
  {
    controlId:   "A1.1",
    framework:   "SOC2" as const,
    category:    "Availability",
    title:       "Availability — Capacity",
    description: "The entity maintains, monitors, and evaluates current processing capacity and use of system components to manage capacity demand.",
    cweIds:      ["CWE-770","CWE-400","CWE-789"],
  },
  {
    controlId:   "PI1.1",
    framework:   "SOC2" as const,
    category:    "Processing Integrity",
    title:       "Processing Integrity",
    description: "The entity obtains or generates, uses, and communicates relevant, quality information to support the functioning of internal control.",
    cweIds:      ["CWE-20","CWE-345","CWE-354"],
  },
];

// Synthetic audit findings spanning 6 months
export const SYNTHETIC_FINDINGS = [
  {
    title:          "SQL Injection in authentication endpoint",
    description:    "Parameterised queries not used in /api/auth/login — user-supplied input concatenated directly into SQL string.",
    severity:       "CRITICAL" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "Developer unfamiliar with ORM parameterisation; no peer review on authentication routes.",
    affectedSystem: "auth-service/src/routes/login.py",
    auditorNotes:   "Found during Q4 2024 external pentest. CVSS 9.8. Immediate patch required.",
    cweId:          "CWE-89",
    controlId:      "CC6.6",
    discoveredAt:   new Date("2024-11-12"),
    remediatedAt:   new Date("2024-11-19"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "Hardcoded AWS credentials in source code",
    description:    "AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY found committed to main branch in config/aws.js.",
    severity:       "CRITICAL" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "Missing pre-commit hook for secret scanning. No developer education on secrets management.",
    affectedSystem: "config/aws.js",
    auditorNotes:   "Credentials rotated immediately. GitHub commit history scrubbed.",
    cweId:          "CWE-798",
    controlId:      "CC6.3",
    discoveredAt:   new Date("2024-11-28"),
    remediatedAt:   new Date("2024-11-29"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "Missing rate limiting on /api/auth/login",
    description:    "Authentication endpoint has no rate limiting — brute force attack possible.",
    severity:       "HIGH" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "Rate limiting deprioritised during MVP phase.",
    affectedSystem: "auth-service/src/routes/login.py",
    auditorNotes:   "Allows unlimited login attempts. Implement express-rate-limit or equivalent.",
    cweId:          "CWE-307",
    controlId:      "CC6.1",
    discoveredAt:   new Date("2024-12-03"),
    remediatedAt:   new Date("2024-12-10"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "XSS via innerHTML in user profile rendering",
    description:    "User-controlled content rendered via innerHTML without sanitisation in profile page.",
    severity:       "HIGH" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "React component bypassed React's default XSS protection using dangerouslySetInnerHTML.",
    affectedSystem: "frontend/src/components/Profile.tsx",
    auditorNotes:   "Medium severity XSS — session hijacking possible.",
    cweId:          "CWE-79",
    controlId:      "CC6.6",
    discoveredAt:   new Date("2024-12-15"),
    remediatedAt:   new Date("2024-12-22"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "JWT signed with 'none' algorithm accepted",
    description:    "API accepts JWTs with algorithm 'none' — attacker can forge tokens without signature.",
    severity:       "CRITICAL" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "JWT library default allowed 'none' algorithm. Algorithm whitelist not configured.",
    affectedSystem: "auth-service/src/middleware/jwt.js",
    auditorNotes:   "Complete authentication bypass possible. P0 — fix immediately.",
    cweId:          "CWE-347",
    controlId:      "CC6.1",
    discoveredAt:   new Date("2025-01-08"),
    remediatedAt:   new Date("2025-01-09"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "SQL Injection re-introduced in search endpoint",
    description:    "SQL injection pattern returned in /api/search — different file, same root cause as Nov finding.",
    severity:       "CRITICAL" as const,
    status:         "OPEN" as const,
    rootCause:      "Fix in auth/login.py was not applied consistently across codebase. Search route uses same pattern.",
    affectedSystem: "api/src/routes/search.py",
    auditorNotes:   "Recurrence of CC6.6 finding. Pattern suggests systemic issue, not isolated bug.",
    cweId:          "CWE-89",
    controlId:      "CC6.6",
    discoveredAt:   new Date("2025-02-14"),
    isRecurring:    true,
    recurrenceCount:1,
  },
  {
    title:          "Wildcard CORS policy on production API",
    description:    "Access-Control-Allow-Origin: * set on all API routes including authenticated endpoints.",
    severity:       "MEDIUM" as const,
    status:         "IN_REMEDIATION" as const,
    rootCause:      "Development CORS config deployed to production. No environment-specific config separation.",
    affectedSystem: "api/src/app.js",
    auditorNotes:   "Allows any website to make credentialed requests. Medium risk but easy to fix.",
    cweId:          "CWE-942",
    controlId:      "CC6.7",
    discoveredAt:   new Date("2025-02-20"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "Insecure deserialization in webhook handler",
    description:    "Python pickle.loads() used to deserialise untrusted webhook payloads.",
    severity:       "CRITICAL" as const,
    status:         "OPEN" as const,
    rootCause:      "Legacy code using pickle for serialisation — developer unaware of security implications.",
    affectedSystem: "webhooks/handler.py",
    auditorNotes:   "Remote code execution possible. Replace with json.loads immediately.",
    cweId:          "CWE-502",
    controlId:      "CC8.1",
    discoveredAt:   new Date("2025-03-01"),
    isRecurring:    false,
    recurrenceCount:0,
  },
  {
    title:          "API key exposed in GitHub Actions logs",
    description:    "STRIPE_SECRET_KEY printed to console in GitHub Actions workflow — visible in public logs.",
    severity:       "CRITICAL" as const,
    status:         "REMEDIATED" as const,
    rootCause:      "Debug console.log left in deployment script. No log scanning in CI/CD pipeline.",
    affectedSystem: ".github/workflows/deploy.yml",
    auditorNotes:   "Secret rotated. Add log scanning to CI. Second secret exposure incident this quarter.",
    cweId:          "CWE-532",
    controlId:      "CC6.3",
    discoveredAt:   new Date("2025-03-10"),
    remediatedAt:   new Date("2025-03-11"),
    isRecurring:    true,
    recurrenceCount:1,
  },
  {
    title:          "Missing authentication on admin API routes",
    description:    "Admin endpoints /api/admin/* accessible without authentication token.",
    severity:       "CRITICAL" as const,
    status:         "OPEN" as const,
    rootCause:      "Auth middleware not applied to admin router. New developer error during refactor.",
    affectedSystem: "api/src/routes/admin.js",
    auditorNotes:   "Any unauthenticated user can access admin functions. Immediate fix required.",
    cweId:          "CWE-306",
    controlId:      "CC6.1",
    discoveredAt:   new Date("2025-03-18"),
    isRecurring:    false,
    recurrenceCount:0,
  },
];

export const SYNTHETIC_REMEDIATIONS = [
  {
    findingTitle:  "SQL Injection in authentication endpoint",
    action:        "Replaced string concatenation with SQLAlchemy parameterised queries",
    notes:         "All query strings in auth module reviewed and updated. Added SAST rule to CI.",
    performedBy:   "Prashanth",
    outcome:       "RESOLVED",
    performedAt:   new Date("2024-11-19"),
  },
  {
    findingTitle:  "Hardcoded AWS credentials in source code",
    action:        "Rotated credentials, migrated to AWS Secrets Manager, added pre-commit hook",
    notes:         "git history scrubbed with git-filter-repo. All team members notified.",
    performedBy:   "Akshay",
    outcome:       "RESOLVED",
    performedAt:   new Date("2024-11-29"),
  },
  {
    findingTitle:  "JWT signed with 'none' algorithm accepted",
    action:        "Pinned JWT algorithm to RS256, added algorithm whitelist in middleware",
    notes:         "All existing tokens invalidated. New tokens issued with forced RS256.",
    performedBy:   "Prashanth",
    outcome:       "RESOLVED",
    performedAt:   new Date("2025-01-09"),
  },
];

export async function seedAuditData(workspaceId: string) {
  console.log("Seeding AuditReady data for workspace:", workspaceId);

  // upsert controls
  for (const ctrl of SOC2_CONTROLS) {
    await db.complianceControl.upsert({
      where: { workspaceId_controlId_framework: {
        workspaceId, controlId: ctrl.controlId, framework: ctrl.framework,
      }},
      update: {},
      create: { ...ctrl, workspaceId },
    });
  }

  // upsert synthetic findings
  for (const f of SYNTHETIC_FINDINGS) {
    const control = await db.complianceControl.findFirst({
      where: { workspaceId, controlId: f.controlId },
    });

    await db.auditFinding.upsert({
      where: { id: `seed_${workspaceId}_${f.title.slice(0, 20).replace(/\s/g, "_")}` },
      update: {},
      create: {
        id:             `seed_${workspaceId}_${f.title.slice(0, 20).replace(/\s/g, "_")}`,
        workspaceId,
        title:          f.title,
        description:    f.description,
        severity:       f.severity,
        status:         f.status,
        rootCause:      f.rootCause,
        affectedSystem: f.affectedSystem,
        auditorNotes:   f.auditorNotes,
        cweId:          f.cweId,
        controlId:      control?.id ?? null,
        discoveredAt:   f.discoveredAt,
        remediatedAt:   (f as any).remediatedAt ?? null,
        isRecurring:    f.isRecurring,
        recurrenceCount:f.recurrenceCount,
      },
    });
  }

  console.log("AuditReady seed complete");
}